.PHONY: clean All

All:
	@echo "----------Building project:[ p1_proj - Debug ]----------"
	@"$(MAKE)" -f  "p1_proj.mk"
clean:
	@echo "----------Cleaning project:[ p1_proj - Debug ]----------"
	@"$(MAKE)" -f  "p1_proj.mk" clean
